# Generated by Django 2.2.26 on 2022-01-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_exam"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
    ]
